In [ ]:
#practical 6: Implementation of Min-Max Normalization on the records as part of Data Preprocessing

#importing the libraries required to perform the task 
import numpy as np
import pandas as pd

#defining the Min-max normalization function which takes the list as the input parameter
def normalize(x):
    min = float(input("Enter your current minimum value: "))
    max = float(input("Enter your current maximum value: "))
    print("\n===============================================")
    newLowerBound = float(input("Enter your new minimum value: ")) 
    newUpperBound = float(input("Enter your new maximum value: "))
    range = max - min
    newRange = newUpperBound - newLowerBound

    return [((a - min) / range) * newRange + newLowerBound for a in x]


#driver code for the implementation

print("=============Min-Max Normalization===========")

#section 1:Lets create the dataframe for the first university
print("\n ==========Enter the records for University 1===========")
#taking the number of records from user as input
n1= int(input("Enter the number of records you want to normalize:"))
print("\n========================================================")

#name of candidate and performance index is taken in input and appended in the list of name and perform_index
name = [input("Enter the name of candidate "+str(a+1)+" : ") for a in range(n1)]
print("\n=============================================================")
perform_index = [float(input("Enter the performance index of candidate "+str(a+1)+" : ")) for a in range(n1)]
print("\n=============================================================")
#apply normalizing function for perform_index column
normalized_index = normalize(perform_index)

#creating the dataframe 
df = pd.DataFrame(normalized_index,name)
df.columns = ['Performance-Index']

print("\n")
print("\n ==========Enter the records for University 2===========")

#section 2: Lets create the dataframe for the second university as the scaling of index is different
#taking the number of records from user as input
n2= int(input("Enter the number of records you want to normalize:"))
print("\n========================================================")

#name of candidate and performance index is taken in input and appended in the list of name and perform_index
name_2 = [input("Enter the name of candidate "+str(a+1)+" : ") for a in range(n1)]
print("\n=============================================================")
perform_index_2 = [float(input("Enter the performance index of candidate "+str(a+1)+" : ")) for a in range(n1)]
print("\n=============================================================")

#apply normalizing function for perform_index column
normalized_index_2 = normalize(perform_index_2)

#creating the dataframe 
df_2 = pd.DataFrame(normalized_index_2,name_2)
df_2.columns = ['Performance-Index']


#section 3: appending the both dataframes:

frames = [df,df_2]
final_df = pd.concat(frames)

#section 4: sorting the records as per performindex column in descending order to give the merit number

result = final_df.sort_values('Performance-Index', ascending=False, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)

print("===========The Final Merit after Normalization==========")
display(result)

=============Min-Max Normalization===========

 ==========Enter the records for University 1===========
Enter the number of records you want to normalize:4

========================================================
Enter the name of candidate 1 : A
Enter the name of candidate 2 : C
Enter the name of candidate 3 : E
Enter the name of candidate 4 : G

=============================================================
Enter the performance index of candidate 1 : 9.1
Enter the performance index of candidate 2 : 4.0
Enter the performance index of candidate 3 : 5.4
Enter the performance index of candidate 4 : 7.2

=============================================================
Enter your current minimum value: 0
Enter your current maximum value: 10
Enter your new minimum value: 0
Enter your new maximum value: 100



 ==========Enter the records for University 2===========
Enter the number of records you want to normalize:4

========================================================
Enter the name of candidate 1 : B
Enter the name of candidate 2 : D
Enter the name of candidate 3 : F
Enter the name of candidate 4 : H

=============================================================
Enter the performance index of candidate 1 : 3.7
Enter the performance index of candidate 2 : 2.1
Enter the performance index of candidate 3 : 3.8
Enter the performance index of candidate 4 : 3.1

=============================================================
Enter your current minimum value: 0
Enter your current maximum value: 4
Enter your new minimum value: 0
Enter your new maximum value: 100
===========The Final Merit after Normalization==========

   Performance-Index
F               95.0
B               92.5
A               91.0
H               77.5
G               72.0
E               54.0
D               52.5
C               40.0